image {
  hdf5: "/mnt/home/cwindolf/data/raw/2941_7380_2836_300.h5:raw"
}
image_mean: 128
image_stddev: 33
checkpoint_interval: 1800
seed_policy: "PolicyPeaks"
model_checkpoint_path: "/mnt/home/cwindolf/data/ffntrain/model.ckpt-4000010"
model_name: "convstack_3d.ConvStack3DFFNModel"
model_args: "{\"depth\": 12, \"fov_size\": [33, 33, 33], \"deltas\": [8, 8, 8]}"
segmentation_output_dir: "/mnt/home/cwindolf/data/ffnres/"
inference_options {
  init_activation: 0.95
  pad_value: 0.05
  move_threshold: 0.9
  min_boundary_dist { x: 2 y: 2 z: 2 }
  segment_threshold: 0.4
  min_segment_size: 100
}
